apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://api.cluster2.chx.osecloud.com:6443
  project: default
  source:
    path: karvgo/cluster-config
    repoURL: https://github.com/christianh814/gitops-examples
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
